baseURL: /
languageCode: ru-ru
defaultContentLanguage: ru
defaultContentLanguageInSubdir: false
title: Flexy
theme: hugo-simple-doc
pygmentsCodeFences: true
pygmentsUseClasses: true
enableMissingTranslationPlaceholders: false
permalinks:
    post: '/:sections/:filename'
params:
    editURL: 'https://github.com/studio107/flexy/edit/master/content/'
    ordersectionsby: weight
    enableGitInfo: true
    analytics_yandex: '47511355'
    analytics_google: UA-6744947-18
outputs:
    home: ["HTML", "RSS", "JSON"]
menu:
    header:
        - { name: Github, url: 'https://github.com/studio107/flexy' }
